<?php
/**
 * Writes deprecated/classmap.php: the file of every 2.x class in deprecated/, for LegacyClassLoader.
 *
 * Run it with `composer legacy:classmap` after adding or removing a class in deprecated/. A unit test fails when the
 * map is out of date.
 *
 * @package RelatedPostsForWP
 */

$rp4wp_dir     = dirname( __DIR__ ) . '/deprecated';
$rp4wp_classes = array_map(
	static function ( $file ) {
		return basename( $file, '.php' );
	},
	glob( $rp4wp_dir . '/RP4WP*.php' )
);
sort( $rp4wp_classes, SORT_STRING );

$rp4wp_width = max( array_merge( [ 0 ], array_map( 'strlen', $rp4wp_classes ) ) ) + 2;
$rp4wp_lines = array_map(
	static function ( $class_name ) use ( $rp4wp_width ) {
		return "\t" . str_pad( "'{$class_name}'", $rp4wp_width ) . " => __DIR__ . '/{$class_name}.php',";
	},
	$rp4wp_classes
);

$rp4wp_php = "<?php\n/**\n * The file of every 2.x class, for LegacyClassLoader. Generated by `composer legacy:classmap`; do not edit.\n *\n * @package RelatedPostsForWP\n */\n\n";
$rp4wp_php .= $rp4wp_lines ? "return [\n" . implode( "\n", $rp4wp_lines ) . "\n];\n" : "return [];\n";

file_put_contents( $rp4wp_dir . '/classmap.php', $rp4wp_php );

echo 'Wrote ' . count( $rp4wp_classes ) . " classes to deprecated/classmap.php.\n";
